include("scenario_1.jl")
include("scenario_2.jl")
include("scenario_3.jl")
include("scenario_4.jl")
include("scenario_5.jl")
include("scenario_6.jl")
include("scenario_7.jl")
include("scenario_8.jl")
include("scenario_9.jl")
include("scenario_10.jl")

scenario_1_potencia_two_biomarkers()
println("Escenario 1 finalizado")
scenario_2_potencia_two_biomarkers()
println("Escenario 2 finalizado")
scenario_3_potencia_two_biomarkers()
println("Escenario 3 finalizado")
scenario_4_potencia_two_biomarkers()
println("Escenario 4 finalizado")

scenario_5_potencia_two_biomarkers()
println("Escenario 5 finalizado")
scenario_6_potencia_two_biomarkers()
println("Escenario 6 finalizado")
scenario_7_potencia_two_biomarkers()
println("Escenario 7 finalizado")
scenario_8_potencia_two_biomarkers()
println("Escenario 8 finalizado")
scenario_9_potencia_two_biomarkers()
println("Escenario 9 finalizado")
scenario_10_potencia_two_biomarkers()
println("Escenario 10 finalizado")